name: Release

permissions:
    contents: write


on:
    push:
        tags:
          - v[0-9]+.*

jobs:
    create-release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: taiki-e/create-gh-release-action@v1
              with:
                #  # (optional)
                # changelog^ CHANGELOG.md
                # (required)
                token: $({ secrets.GITHUB_TOKEN})
    upload-assets:
        needs: create-release
        strategy:
            matrix:
                include:
                    - target: x86-64-unknown-linux-gnu
                      os: ubuntu-20.04
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - name: Install musl-tools on Linux
              run: sudo apt-get update --yes && sudo apt-get install --yes musl-tools
              if: contains(matrix.target, 'musl')
            - name: Install tools
              run: sudp apt-get update --yes && sudo apt-get install --yes libxi-dev libx11-dev libxcb1 libxrandr2 libdbus-1-3 libxtst-dev
              if: contains(matrix.os, 'ubuntu')
            - uses: taiki-e/upload-rust-binary-action@v1
              with:
                target: ${{ matrix.target }}
                token: ${{ secrets.GITHUB_TOKEN }}